import { SITE, CATEGORIES, PRODUCTS } from "./data.js";
let active="all",wishlist=JSON.parse(localStorage.getItem("maisonWishlist")||"[]");
const $=id=>document.getElementById(id);
function renderCategories(){$("categoryGrid").innerHTML=CATEGORIES.map(c=>`<a class="category ${c.tone}" href="catalog.html?category=${c.id}"><div class="cat-art"></div><div><small>${c.sub}</small><b>${c.name}</b><span>Explore →</span></div></a>`).join("")}
function renderFilters(){$("filters").innerHTML=`<button class="filter ${active==="all"?"active":""}" onclick="setCategory('all')">All</button>`+CATEGORIES.map(c=>`<button class="filter ${active===c.id?"active":""}" onclick="setCategory('${c.id}')">${c.name}</button>`).join("")}
function renderProducts(){let list=PRODUCTS.filter(p=>active==="all"||p.cat===active),q=$("search").value.toLowerCase().trim();if(q)list=list.filter(p=>(p.name+" "+p.id+" "+categoryName(p.cat)).toLowerCase().includes(q));if($("sort").value==="az")list=[...list].sort((a,b)=>a.name.localeCompare(b.name));if($("sort").value==="low")list=[...list].sort((a,b)=>a.price-b.price);if($("sort").value==="high")list=[...list].sort((a,b)=>b.price-a.price);$("products").innerHTML=list.slice(0,6).map(p=>`<article class="card"><div class="photo"><a href="product.html?id=${p.id}"><img src="${p.images[0] || "../assets/jaipur-prints-logo.jpg"}" alt="${p.name}" onerror="this.src='../assets/jaipur-prints-logo.jpg'"></a>${p.badge?`<span class="badge">${p.badge}</span>`:""}<button class="heart ${wishlist.includes(p.id)?"saved":""}" onclick="toggleWish('${p.id}',event)">${wishlist.includes(p.id)?"♥":"♡"}</button></div><div class="card-body"><div class="meta">${categoryName(p.cat)} <span>${p.id}</span></div><h3><a href="product.html?id=${p.id}">${p.name}</a></h3><p>${p.desc}</p><div class="card-foot"><b>${money(p.price)}</b><a href="${waLink(p)}" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a></div></div></article>`).join("")}
function setCategory(c){active=c;renderFilters();renderProducts()}
function toggleWish(id,e){e.stopPropagation();wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];localStorage.setItem("maisonWishlist",JSON.stringify(wishlist));updateWish();renderProducts();showWishlist()}
function updateWish(){$("wishCount").textContent=wishlist.length}
function showWishlist(){$("wishlistModal").classList.add("show");$("wishlistItems").innerHTML=wishlist.length?wishlist.map(id=>{let p=productById(id);return p?`<div class="wish-row"><img src="${p.images[0]}"><div><b>${p.name}</b><span>${money(p.price)}</span><a href="${waLink(p)}" target="_blank" rel="noopener noreferrer">Order on WhatsApp ↗</a></div><button onclick="toggleWish('${p.id}',event)">×</button></div>`:""}).join(""):"<div class='empty-wish'>Your wishlist is empty.</div>"}
function closeWishlist(e){if(!e||e.target===$("wishlistModal"))$("wishlistModal").classList.remove("show")}
function openWhatsApp(){const url=waBase();window.open(url,"_blank","noopener,noreferrer")}
function toggleMenu(){$("mobileMenu").classList.toggle("open")}
$("topWa").href=waBase();$("contactWa").href=waBase();$("year").textContent=new Date().getFullYear();$("search").addEventListener("input",renderProducts);$("sort").addEventListener("change",renderProducts);renderCategories();renderFilters();renderProducts();updateWish();
